### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by Yoghurt4C** [Magneticraft-Team/Magneticraft#136]
Description: Exception ticking world

java.lang.NoClassDefFoundError: com/cout970/magneticraft/util/vector/Vec3iKt
    at com.cout970.magneticraft.world.OilSourceGenerator.placeBlocks(OilSourceGenerator.kt:54)
    at com.cout970.magneticraft.world.OilSourceGenerator.generate(OilSourceGenerator.kt:40)
    at com.cout970.magneticraft.world.WorldGenerator.generate(WorldGenerator.kt:31)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1018)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:997)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.cout970.magneticraft.util.vector.Vec3iKt
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
Caused by: java.lang.NullPointerException

**Comment by cout970** [comment]
wtf? so 1 class disappeared for no reason? 

can you provide the complete crash log? so I can check the installed mods and installed coremods.
Also please upload the log to a page like https://hastebin.com/ and share the link instead of pasting the whole text here

**Comment by Yoghurt4C** [comment]
sorry, had to pull the log from the server
https://paste.dimdev.org/nahewitaru.rb

**Comment by cout970** [comment]
Apparently sometimes gradle uses a class cache to avoid recompiling  the whole mod, so it's possible for some classes to not be included in the final jar, this shouldn't happen in recent versions.
