### ISSUE TITLE
Mod crashing at startup

### ISSUE THREAD

**Issue by redragon309** [Magneticraft-Team/Magneticraft#141]
It would seem like when I launch the game, after FLM would initilize the mods, the launcher would crash and return back to the main launcher menu.   Here is part of the crash report (The full details can be found at the attachment):

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at com.cout970.magneticraft.registry.TileEntitiesKt$initTileEntities$2.accept(TileEntities.kt:47)
	at com.cout970.magneticraft.registry.TileEntitiesKt$initTileEntities$2.accept(TileEntities.kt)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at com.cout970.magneticraft.registry.TileEntitiesKt.initTileEntities(TileEntities.kt:46)
	at com.cout970.magneticraft.proxy.CommonProxy$postItemRegister$2.invoke(CommonProxy.kt:44)
	at com.cout970.magneticraft.proxy.CommonProxy$postItemRegister$2.invoke(CommonProxy.kt:26)
	at com.cout970.magneticraft.util.LoggerKt.logTime(Logger.kt:41)
	at com.cout970.magneticraft.proxy.CommonProxy.postItemRegister(CommonProxy.kt:44)
	at com.cout970.magneticraft.proxy.ClientProxy.postItemRegister(ClientProxy.kt:49)
	at com.cout970.magneticraft.proxy.CommonProxy.initItemsEvent(CommonProxy.kt:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1504_CommonProxy_initItemsEvent_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full Report:
[crash-2018-09-28_15.13.30-client.txt](https://github.com/Magneticraft-Team/Magneticraft/files/2429517/crash-2018-09-28_15.13.30-client.txt)

**Comment by redragon309** [comment]
EDIT:

I solved the problem.  Had to update forge to a newer version!
