### ISSUE TITLE
gmae crash

### ISSUE THREAD

**Issue by gimlisan** [Magneticraft-Team/Magneticraft#2]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/21/16 2:27 PM
Description: Initializing game

Reika.DragonAPI.Exception.IDConflictException: RotaryCraft was not installed correctly:
CONFLICT: Potion IDs: com.emoniph.witchery.brewing.potions.PotionSprouting@16fbcb6 @ 35 (PotionSprouting & FreezePotion)
Check your IDs and change them if possible.
This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..
   at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.onConflict(PotionCollisionTracker.java:78)
   at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.check(PotionCollisionTracker.java:68)
   at Reika.DragonAPI.DragonAPIInit.postload(DragonAPIInit.java:582)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
   at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
   at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
   at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
   at net.minecraft.client.main.Main.main(SourceFile:148)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
   at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.onConflict(PotionCollisionTracker.java:78)
   at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.check(PotionCollisionTracker.java:68)
   at Reika.DragonAPI.DragonAPIInit.postload(DragonAPIInit.java:582)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
   at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
   at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
   at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
   at net.minecraft.client.main.Main.main(SourceFile:148)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Cypher121** [comment]
> 1.7.10 mods
> 1.8/1.9 repository
> Reika.DragonAPI.Exception.IDConflictException
> This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..

Guess fucking what.

**Comment by Cypher121** [comment]
@ReikaKalseki perhaps this line would benefit from being repeated 10 more times. [Also I see you're having fun too.](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/805)

**Comment by ReikaKalseki** [comment]
At least he managed to install it in the correct MC version this time...
