### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by HurtsAsHell** [Magneticraft-Team/Magneticraft#94]
Caused by: java.lang.NoClassDefFoundError: com/blamejared/mtlib/helpers/InputHelper
	at com.cout970.magneticraft.integration.crafttweaker.UtilitiesKt.toStack(Utilities.kt:33)
	at com.cout970.magneticraft.integration.crafttweaker.CrushingTable$addRecipe$1.invoke(CrushingTable.kt:22)
	at com.cout970.magneticraft.integration.crafttweaker.CrushingTable$addRecipe$1.invoke(CrushingTable.kt:16)
	at com.cout970.magneticraft.integration.crafttweaker.CraftTweakerPlugin.runActions(CraftTweakerPlugin.kt:13)
	at com.cout970.magneticraft.integration.IntegrationHandler.init(IntegrationHandler.kt:26)
	at com.cout970.magneticraft.Magneticraft.init(Magneticraft.kt:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.blamejared.mtlib.helpers.InputHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 54 more
Caused by: java.lang.NullPointerException

The error was caused from craftweaker

mods.magneticraft.CrushingTable.addRecipe(<extendedcrafting:material>, <extendedcrafting:material:2>, false);

What's the problem?

**Comment by cout970** [comment]
There are several possible problems, since I don't know which versions and mods do you have installed is hard to tell exactly, the error is caused by the mod being unable to access mtlib, maybe the library is missing?.Other possibility is that the API changed, I don't know that versions of magneticraft, crafttweaker or mtlib do you have installed so i can only guess. Also i found a bug in the 2.1.0 version about craftweaker when it was not present. but again, i need more info.

What are the mods are installed?
What are the versions of the mods installed?
What is the version of Magneticraft?
What did you do to produce the error? start the game, open a world, use a machines, etc.

**Comment by HurtsAsHell** [comment]
i need mtlib?

**Comment by HurtsAsHell** [comment]
okay; I added the mtlib (it was not required to install the mod) and I updated the magneticraft to the latest version and now it goes.

Thanks,I'm sorry for the trouble.
